/**
 * Filesystem output mode (the default): write real `.auto.stories.*` files next
 * to each component, governed by the manifest.
 *
 * Rules:
 * - Generated files use the `.auto.stories.<ext>` suffix and a banner, so they
 *   never collide with hand-written `.stories.<ext>` files.
 * - Components that already have a manual story are skipped.
 * - Freeze-on-edit: if a generated file's current content no longer matches the
 *   hash we recorded when we wrote it, the user has edited it by hand — we leave
 *   it alone and never clobber their changes.
 * - Each file's governance status (surfaced/in-review/approved) comes from the
 *   manifest and decides its sidebar group.
 */

import fs from 'node:fs';
import path from 'node:path';
import { generateComponentStory } from './generator.js';
import { contentHash } from './hash.js';
import { logger } from './logger.js';
import { loadManifest, saveManifest, ensureEntry, componentKey } from './governance.js';

const BANNER = 'Auto-generated by storybook-addon-auto-detect';

/**
 * @param adapter
 * @param components
 * @param options  Validated options (must include configDir + projectRoot).
 * @param getContext  (component) => { status, group, drifted, instances, conformance }
 */
export function writeStoryFiles(adapter, components, options, getContext = () => ({})) {
  const manifest = loadManifest(options.configDir);
  const written = [];

  for (const component of components) {
    if (component.manualStory) {
      logger.debug(`manual story exists for <${component.name}>, skipping generation`);
      continue;
    }

    const key = componentKey(component, options.projectRoot);
    const entry = ensureEntry(manifest, key);
    const ctx = getContext(component);

    const dir = path.dirname(component.filePath);
    const base = path.basename(component.filePath, path.extname(component.filePath));
    const storyPath = path.join(dir, `${base}.auto.stories.${adapter.storyExtension}`);

    const code = generateComponentStory(adapter, component, options, {
      importSpecifier: `./${base}`,
      ...ctx,
    });

    // Only guard against clobbering a NON-generated file (no banner). The
    // generated `.auto.stories.*` are addon-owned throwaways and always
    // regenerate, so they never drift out of sync with config/source.
    if (fs.existsSync(storyPath) && !safeRead(storyPath).includes(BANNER)) {
      logger.warn(`refusing to overwrite non-generated file ${storyPath}`);
      continue;
    }

    try {
      fs.writeFileSync(storyPath, code, 'utf8');
      entry.generatedHash = contentHash(code);
      entry.edited = false;
      entry.file = path.relative(options.projectRoot, component.filePath).split(path.sep).join('/');
      written.push(storyPath);
      logger.debug(`wrote ${path.relative(options.projectRoot, storyPath)} [${ctx.status || 'surfaced'}]`);
    } catch (err) {
      logger.warn(`could not write ${storyPath}: ${err.message}`);
    }
  }

  saveManifest(options.configDir, manifest);
  logger.info(`filesystem mode: wrote ${written.length} story file(s)`);
  return written;
}

function safeRead(filePath) {
  try {
    return fs.readFileSync(filePath, 'utf8');
  } catch {
    return '';
  }
}
