/**
 * Optional Tailwind v4 auto-wiring.
 *
 * By default the addon stays out of styling — it only generates the `@theme`
 * token sheet and lets the host repo own Tailwind (the "team-owned setup"). But
 * onboarding a brand-new repo then means hand-wiring `@tailwindcss/vite` and a
 * CSS entry. With `tailwind: true` the addon does both for you: it injects the
 * Tailwind v4 Vite plugin and loads `tailwindcss` + the generated token theme
 * into the preview — so the only setup is the one option.
 *
 * Everything here is guarded: if the repo already wired Tailwind we stay out of
 * the way (never double-inject), and if the Tailwind packages aren't installed
 * we warn and no-op rather than breaking the build.
 */

import fs from 'node:fs';
import path from 'node:path';
import { logger } from './logger.js';

const BANNER = 'Auto-generated by storybook-addon-auto-detect';

/**
 * Is the Tailwind v4 Vite plugin already present? The `@tailwindcss/vite`
 * factory returns several sub-plugins whose names are prefixed `@tailwindcss/vite`,
 * so we flatten and match on that prefix.
 */
export function hasTailwindPlugin(plugins = []) {
  return flatten(plugins).some(
    (p) => p && typeof p.name === 'string' && p.name.startsWith('@tailwindcss/vite'),
  );
}

function flatten(arr) {
  const out = [];
  for (const item of arr || []) {
    if (Array.isArray(item)) out.push(...flatten(item));
    else out.push(item);
  }
  return out;
}

/**
 * Instantiate `@tailwindcss/vite`, or return null if it isn't installed. Kept
 * async + dynamic so the package is a true optional dependency.
 */
export async function loadTailwindPlugin() {
  try {
    const mod = await import('@tailwindcss/vite');
    const factory = mod.default || mod;
    return typeof factory === 'function' ? factory() : null;
  } catch {
    return null;
  }
}

/**
 * Write the preview entry that pulls Tailwind + the generated token theme into
 * the Storybook preview, and return the JS entry path (to add via
 * `previewAnnotations`). The CSS sits next to the generated `auto-theme.css` so
 * the relative `@import` resolves.
 *
 * @returns {string|null} absolute path to the preview JS entry, or null on failure.
 */
export function writeTailwindPreview(options) {
  const themeOut = path.resolve(options.projectRoot, options.themeOutput || 'src/auto-theme.css');
  const dir = path.dirname(themeOut);
  const cssPath = path.join(dir, 'auto-tailwind.css');
  const jsPath = path.join(dir, 'auto-tailwind-preview.js');
  const themeBase = path.basename(themeOut);
  try {
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(
      cssPath,
      `/* ${BANNER}. Do not edit by hand. */\n@import "tailwindcss";\n@import "./${themeBase}";\n`,
      'utf8',
    );
    fs.writeFileSync(
      jsPath,
      `// ${BANNER}. Do not edit by hand.\nimport './auto-tailwind.css';\n`,
      'utf8',
    );
  } catch (err) {
    logger.warn(`tailwind: could not write preview entry: ${err.message}`);
    return null;
  }
  return jsPath;
}

/**
 * Inject the Tailwind v4 Vite plugin into a Storybook Vite config when
 * `tailwind: true` — unless the host already wired it. Mutates and returns the
 * config. No-ops (with a clear warning) if the packages aren't installed.
 */
export async function injectTailwind(config, options) {
  if (!options.tailwind) return config;
  if (hasTailwindPlugin(config.plugins)) {
    logger.debug('tailwind: host already wired @tailwindcss/vite — leaving it alone');
    return config;
  }
  const plugin = await loadTailwindPlugin();
  if (!plugin) {
    logger.warn(
      'tailwind: option is on but @tailwindcss/vite is not installed — run ' +
        '`npm i -D tailwindcss @tailwindcss/vite` (or unset `tailwind`).',
    );
    return config;
  }
  config.plugins = config.plugins || [];
  config.plugins.push(plugin);
  logger.info('tailwind: injected @tailwindcss/vite');
  return config;
}
