/**
 * Design tokens — the addon owns a `tokens.json` source of truth and GENERATES
 * a Tailwind v4 `@theme` stylesheet from it. It never edits the team's Tailwind
 * config; the team `@import`s the generated file once and the addon keeps it
 * current as tokens are edited in the Storybook UI.
 *
 *   tokens.json  ->  auto-theme.css  ->  `bg-brand-600` etc. resolve
 */

import fs from 'node:fs';
import path from 'node:path';

const TOKENS_FILE = 'tokens.json';
const BANNER = 'Auto-generated by storybook-addon-auto-detect';

export function tokensPath(configDir) {
  return path.join(configDir, TOKENS_FILE);
}

export function loadTokens(configDir) {
  try {
    const data = JSON.parse(fs.readFileSync(tokensPath(configDir), 'utf8'));
    if (!data.colors) data.colors = {};
    if (!data.spacing) data.spacing = {};
    return data;
  } catch {
    return { colors: {}, spacing: {} };
  }
}

export function saveTokens(configDir, tokens) {
  fs.writeFileSync(tokensPath(configDir), `${JSON.stringify(tokens, null, 2)}\n`, 'utf8');
}

/**
 * Normalize a spacing token value to a CSS length. A bare number (or numeric
 * string) is treated as pixels (`16` → `16px`); anything with a unit or multiple
 * parts passes through untouched (`'0 0 8px'`, `'0.5rem'`).
 */
function formatSpacing(value) {
  const str = String(value).trim();
  return /^-?\d+(\.\d+)?$/.test(str) ? `${str}px` : str;
}

/** Render a Tailwind v4 `@theme` block from the token set. */
export function generateThemeCss(tokens) {
  const lines = [`/* ${BANNER}. Do not edit by hand. */`, '@theme {'];
  for (const [name, value] of Object.entries(tokens.colors || {})) {
    lines.push(`  --color-${name}: ${value};`);
  }
  for (const [name, value] of Object.entries(tokens.spacing || {})) {
    lines.push(`  --spacing-${name}: ${formatSpacing(value)};`);
  }
  lines.push('}', '');
  return lines.join('\n');
}

/** Write the generated stylesheet to the configured output path. */
export function writeThemeCss(options) {
  const tokens = loadTokens(options.configDir);
  const out = path.resolve(options.projectRoot, options.themeOutput || 'src/auto-theme.css');
  try {
    fs.writeFileSync(out, generateThemeCss(tokens), 'utf8');
  } catch {
    /* output dir may not exist yet — ignore */
  }
  return { out, tokens: tokens.colors };
}

/**
 * A self-contained Storybook story that renders an interactive token editor in
 * the canvas — a central place to *see and configure* the theme. Swatches use
 * `var(--color-<name>)`, so they recolor live as tokens change.
 */
export function generateTokensStory(tokens) {
  const initial = JSON.stringify(tokens.colors || {}, null, 2);
  return `// ${BANNER}. Do not edit by hand.
import React from 'react';
import { addons } from 'storybook/preview-api';

const INITIAL = ${initial};

function TokenEditor() {
  const [tokens, setTokens] = React.useState(INITIAL);
  const [name, setName] = React.useState('');
  const [value, setValue] = React.useState('#7c3aed');
  const channel = addons.getChannel();
  React.useEffect(() => {
    const onTokens = (live) => { if (live) setTokens(live); };
    channel.on('auto-detect/tokens', onTokens);
    channel.emit('auto-detect/get-tokens', {});
    return () => channel.off('auto-detect/tokens', onTokens);
  }, []);
  const set = (n, v) => {
    setTokens((t) => ({ ...t, [n]: v }));
    channel.emit('auto-detect/set-token', { name: n, value: v });
  };
  const remove = (n) => {
    setTokens((t) => { const next = { ...t }; delete next[n]; return next; });
    channel.emit('auto-detect/set-token', { name: n, remove: true });
  };
  const add = () => { if (name) { set(name, value); setName(''); } };
  const cell = { padding: '6px 10px', borderBottom: '1px solid #eee', textAlign: 'left' };

  return (
    <div style={{ fontFamily: 'system-ui, sans-serif', fontSize: 13, maxWidth: 560 }}>
      <h2 style={{ marginTop: 0 }}>
        Design tokens{' '}
        <span style={{ color: '#6b7280', fontWeight: 400, fontSize: 13 }}>(Tailwind @theme · colors)</span>
      </h2>
      <table style={{ borderCollapse: 'collapse', width: '100%' }}>
        <tbody>
          {Object.entries(tokens).map(([n, v]) => (
            <tr key={n}>
              <td style={cell}>
                <div style={{ height: 24, width: 24, borderRadius: 4, border: '1px solid #ddd', background: 'var(--color-' + n + ')' }} />
              </td>
              <td style={cell}><code>--color-{n}</code></td>
              <td style={cell}>
                <input type="color" value={String(v).slice(0, 7)} onChange={(e) => set(n, e.target.value)} style={{ verticalAlign: 'middle' }} />
                <code style={{ marginLeft: 8 }}>{v}</code>
              </td>
              <td style={cell}>
                <button type="button" onClick={() => remove(n)} style={{ cursor: 'pointer' }}>✕</button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
      <div style={{ marginTop: 12, display: 'flex', gap: 8, alignItems: 'center' }}>
        <input placeholder="name (e.g. accent-500)" value={name} onChange={(e) => setName(e.target.value)} style={{ padding: '4px 8px' }} />
        <input type="color" value={value} onChange={(e) => setValue(e.target.value)} />
        <button type="button" onClick={add} style={{ cursor: 'pointer', fontWeight: 600 }}>Add token</button>
      </div>
      <p style={{ color: '#6b7280', fontSize: 12 }}>
        Edits write <code>.storybook/tokens.json</code> and regenerate the <code>@theme</code> stylesheet; everything using the token recolors live.
      </p>
    </div>
  );
}

export default { title: 'Design System/Tokens', tags: ['tokens'] };
export const Tokens = { name: 'Tokens', render: () => <TokenEditor /> };
`;
}

/** Write the interactive tokens story next to the generated stylesheet. */
export function writeTokensStory(options) {
  const tokens = loadTokens(options.configDir);
  const themeOut = path.resolve(options.projectRoot, options.themeOutput || 'src/auto-theme.css');
  const out = path.join(path.dirname(themeOut), 'tokens.auto.stories.jsx');
  try {
    fs.writeFileSync(out, generateTokensStory(tokens), 'utf8');
  } catch {
    /* ignore */
  }
  return out;
}
