/**
 * React adapter.
 *
 * - Discovery: .jsx/.tsx/.js/.ts files whose exports look like components.
 * - Prop analysis: delegated to `react-docgen`, which natively understands
 *   TypeScript interfaces/types, PropTypes, and JSDoc comments.
 * - Story rendering: emits CSF3 source.
 *
 * Parsing is purely static (react-docgen builds a Babel AST and never executes
 * the module), so circular imports and side-effectful modules are safe.
 */

import path from 'node:path';
import { parse, builtinResolvers } from 'react-docgen';
import { logger } from '../logger.js';
import { toStoryExport } from '../naming.js';

const COMPONENT_EXTENSIONS = ['jsx', 'tsx', 'js', 'ts'];

// react-docgen's resolver that returns every exported component definition in a
// file (limit: 0 == no cap), so a file exporting several components yields all.
const resolver = new builtinResolvers.FindExportedDefinitionsResolver({ limit: 0 });

export const reactAdapter = {
  name: 'react',
  fileExtensions: COMPONENT_EXTENSIONS,
  storyExtension: 'jsx',

  matches(deps) {
    return Boolean(deps.react);
  },

  /**
   * Cheap pre-filter. `parse` is the authoritative check (returns [] for
   * non-components), so this just rejects obvious non-candidates.
   */
  isComponentFile(filePath) {
    const base = path.basename(filePath);
    const ext = path.extname(filePath).slice(1);
    if (!COMPONENT_EXTENSIONS.includes(ext)) return false;
    if (/\.(stories|story|test|spec|d)\./.test(base)) return false;
    // Components are PascalCase by convention; index.* re-exports are skipped.
    if (/^index\./.test(base)) return false;
    return true;
  },

  parse(filePath, source) {
    let docs;
    try {
      docs = parse(source, { filename: filePath, resolver });
    } catch (err) {
      // A parse failure for one file must never abort the whole scan.
      logger.debug(`react-docgen could not parse ${filePath}: ${err.message}`);
      return [];
    }

    const exportsInfo = detectExports(source);

    return docs
      .filter((doc) => doc.displayName)
      .map((doc) => {
        const exportName = resolveExportName(doc.displayName, exportsInfo);
        return {
          name: doc.displayName,
          exportName: exportName.name,
          isDefaultExport: exportName.isDefault,
          filePath,
          description: doc.description || '',
          props: normalizeProps(doc.props || {}),
        };
      });
  },

  /**
   * Render a story plan (computed by the shared generator) into CSF3 source.
   * @param {import('./registry.js').ComponentInfo} component
   * @param {{ importSpecifier: string, stories: Array<{name:string,args:object}>, tags:string[], title:string }} ctx
   */
  generateStoryCode(component, ctx) {
    const importLine = component.isDefaultExport
      ? `import ${component.name} from '${ctx.importSpecifier}';`
      : `import { ${component.exportName} } from '${ctx.importSpecifier}';`;
    const componentRef = component.isDefaultExport ? component.name : component.exportName;

    const metaLines = [
      `const meta = {`,
      `  title: ${JSON.stringify(ctx.title)},`,
    ];
    // Stable, status-independent id so the sidebar groups by title but URLs
    // don't change when a component is promoted between status groups.
    if (ctx.metaId) metaLines.push(`  id: ${JSON.stringify(ctx.metaId)},`);
    metaLines.push(`  component: ${componentRef},`, `  tags: ${JSON.stringify(ctx.tags)},`);
    if (ctx.parameters) {
      metaLines.push(`  parameters: ${stringifyArgs(ctx.parameters, 1)},`);
    }
    metaLines.push(`};`, `export default meta;`);
    const meta = metaLines.join('\n');

    const stories = ctx.stories
      .map((story) => {
        const exportName = toStoryExport(story.name);
        const argsLiteral = stringifyArgs(story.args, 1);
        const body = Object.keys(story.args).length
          ? `{\n  name: ${JSON.stringify(story.name)},\n  args: ${argsLiteral},\n}`
          : `{\n  name: ${JSON.stringify(story.name)},\n}`;
        return `export const ${exportName} = ${body};`;
      })
      .join('\n\n');

    return [
      '// Auto-generated by storybook-addon-auto-detect. Do not edit by hand.',
      importLine,
      '',
      meta,
      '',
      stories,
      '',
    ].join('\n');
  },
};

// ---------------------------------------------------------------------------
// Prop normalization
// ---------------------------------------------------------------------------

function normalizeProps(rawProps) {
  return Object.entries(rawProps).map(([name, info]) => {
    const { bucket, enumValues, rawType } = classifyType(info);
    return {
      name,
      required: Boolean(info.required),
      tsType: bucket,
      rawType,
      description: info.description || '',
      defaultValue: extractDefault(info),
      enumValues,
    };
  });
}

function extractDefault(info) {
  if (info.defaultValue && info.defaultValue.value !== undefined) {
    const raw = String(info.defaultValue.value).trim();
    // react-docgen gives the source text of the default; keep it as a marker
    // so the generator can decide whether to surface it.
    return raw;
  }
  return undefined;
}

/**
 * Collapse react-docgen's rich type info (TS `tsType` or PropTypes `type`) into
 * a coarse bucket plus any literal enum options.
 */
function classifyType(info) {
  const ts = info.tsType;
  const pt = info.type;

  if (ts) {
    const raw = ts.raw || ts.name || 'unknown';
    const enumValues = extractEnumValues(ts);
    if (enumValues.length) return { bucket: 'enum', enumValues, rawType: raw };
    return { bucket: bucketFromTsName(ts), enumValues: [], rawType: raw };
  }

  if (pt) {
    const raw = pt.raw || pt.name || 'unknown';
    if (pt.name === 'enum' && Array.isArray(pt.value)) {
      const enumValues = pt.value
        .map((v) => unquoteLiteral(v.value))
        .filter((v) => v !== undefined);
      if (enumValues.length) return { bucket: 'enum', enumValues, rawType: raw };
    }
    return { bucket: bucketFromPropType(pt.name), enumValues: [], rawType: raw };
  }

  return { bucket: 'unknown', enumValues: [], rawType: 'unknown' };
}

function extractEnumValues(ts) {
  // Union of string/number literals: { name: 'union', elements: [...] }
  if (ts.name === 'union' && Array.isArray(ts.elements)) {
    const literals = ts.elements
      .filter((el) => el.name === 'literal')
      .map((el) => unquoteLiteral(el.value));
    // Only treat as an enum if every member is a literal (e.g. 'sm' | 'md').
    if (literals.length && literals.length === ts.elements.length) {
      return literals.filter((v) => v !== undefined);
    }
  }
  return [];
}

function bucketFromTsName(ts) {
  switch (ts.name) {
    case 'string':
      return 'string';
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'Array':
    case 'tuple':
      return 'array';
    case 'signature':
      return ts.type === 'function' ? 'func' : 'object';
    case 'ReactElement':
    case 'ReactNode':
    case 'Element':
      return 'node';
    default:
      if (/ReactNode|ReactElement|JSX\.Element/.test(ts.raw || '')) return 'node';
      if (/=>/.test(ts.raw || '')) return 'func';
      return 'unknown';
  }
}

function bucketFromPropType(name) {
  switch (name) {
    case 'string':
      return 'string';
    case 'number':
      return 'number';
    case 'bool':
      return 'boolean';
    case 'func':
      return 'func';
    case 'array':
    case 'arrayOf':
      return 'array';
    case 'object':
    case 'shape':
    case 'objectOf':
      return 'object';
    case 'node':
    case 'element':
      return 'node';
    default:
      return 'unknown';
  }
}

function unquoteLiteral(value) {
  if (value === undefined || value === null) return undefined;
  const str = String(value).trim();
  const m = str.match(/^['"`](.*)['"`]$/);
  if (m) return m[1];
  if (str === 'true') return true;
  if (str === 'false') return false;
  if (/^-?\d+(\.\d+)?$/.test(str)) return Number(str);
  return str;
}

// ---------------------------------------------------------------------------
// Export detection (so generated imports use the right specifier)
// ---------------------------------------------------------------------------

function detectExports(source) {
  const named = new Set();
  let defaultName;

  const namedDecl = /export\s+(?:const|let|var|function|class)\s+([A-Za-z0-9_$]+)/g;
  for (const m of source.matchAll(namedDecl)) named.add(m[1]);

  const namedList = /export\s*\{([^}]+)\}/g;
  for (const m of source.matchAll(namedList)) {
    for (const part of m[1].split(',')) {
      const id = part.trim().split(/\s+as\s+/i).pop().trim();
      if (id) named.add(id);
    }
  }

  const defDecl = source.match(/export\s+default\s+(?:function|class)\s+([A-Za-z0-9_$]+)/);
  const defIdent = source.match(/export\s+default\s+([A-Za-z0-9_$]+)\s*;?/);
  if (defDecl) defaultName = defDecl[1];
  else if (defIdent) defaultName = defIdent[1];
  else if (/export\s+default\s/.test(source)) defaultName = '__anonymous_default__';

  return { named, defaultName };
}

function resolveExportName(displayName, { named, defaultName }) {
  if (defaultName && (defaultName === displayName || defaultName === '__anonymous_default__')) {
    return { name: displayName, isDefault: true };
  }
  if (named.has(displayName)) {
    return { name: displayName, isDefault: false };
  }
  // Fall back to a default import — the most common single-component pattern.
  return { name: displayName, isDefault: true };
}

// ---------------------------------------------------------------------------
// CSF rendering helpers
// ---------------------------------------------------------------------------

/** Serialize an args object to source, handling functions specially. */
function stringifyArgs(args, indent) {
  const pad = '  '.repeat(indent);
  const innerPad = '  '.repeat(indent + 1);
  const entries = Object.entries(args).map(([key, value]) => {
    return `${innerPad}${key}: ${serializeValue(value, indent + 1)}`;
  });
  if (!entries.length) return '{}';
  return `{\n${entries.join(',\n')},\n${pad}}`;
}

function serializeValue(value, indent) {
  if (value && typeof value === 'object' && value.__fn) {
    return '() => {}';
  }
  if (Array.isArray(value)) {
    return `[${value.map((v) => serializeValue(v, indent)).join(', ')}]`;
  }
  if (value && typeof value === 'object') {
    const pad = '  '.repeat(indent + 1);
    const closePad = '  '.repeat(indent);
    const entries = Object.entries(value).map(
      ([k, v]) => `${pad}${JSON.stringify(k)}: ${serializeValue(v, indent + 1)}`,
    );
    return entries.length ? `{\n${entries.join(',\n')},\n${closePad}}` : '{}';
  }
  return JSON.stringify(value);
}
